---
title: "p8105_hw2_kxg2002.Rmd"
author: "Katie"
date: "10/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl) 
library(dplyr)
```

## Load in the trash wheel data 

```{r}
trash_wheel_data = 
  read_excel(
    path = "./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
    range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  select(-homes_powered) %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = as.integer(sports_balls))
```

## Read and clean 2017 and 2018 precip data 

```{r}
precip_data_2017 = 
  read_excel(
    path = "./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",  
    sheet = 6, 
    range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = "2017") 
  
  
precip_data_2018 = 
  read_excel(
    path = "./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
    sheet = 5, 
    range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>%  
  mutate(year = "2018") 
```


